/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package constants.programs;

import client.MapleCharacter;
import client.MapleClient;
import constants.ServerConstants;
import database.MYSQL;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.concurrent.ScheduledFuture;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import launch.ChannelServer;
import launch.world.WorldBroadcasting;
import launch.world.WorldCommunity;
import packet.creators.MainPacketCreator;
import packet.creators.UIPacket;
import packet.opcode.RecvPacketOpcode;
import packet.opcode.SendPacketOpcode;
import server.maps.MapleMap;
import tools.Timer;

/**
 *
 * @author Administrator
 */
public class ControlUnit extends javax.swing.JFrame {

	public ControlUnit() {
		Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
		this.setLocation((screenSize.width - 1505) / 2, (screenSize.height - 576) / 2);
		initComponents();
		서버정보불러오기();
		환율정보();
		채팅금지();
		벤();
		this.setTitle("[ArcStoryDEV]Server_Emulator :: V1.2." + ServerConstants.MAPLE_VERSION);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jButton1 = new javax.swing.JButton();
		jTextField1 = new javax.swing.JTextField();
		jTextField2 = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jTextField3 = new javax.swing.JTextField();
		jButton2 = new javax.swing.JButton();
		jLabel3 = new javax.swing.JLabel();
		jTextField4 = new javax.swing.JTextField();
		jButton3 = new javax.swing.JButton();
		jTextField5 = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jTextField6 = new javax.swing.JTextField();
		jTextField7 = new javax.swing.JTextField();
		jButton4 = new javax.swing.JButton();
		jLabel5 = new javax.swing.JLabel();
		jTextField8 = new javax.swing.JTextField();
		jTextField9 = new javax.swing.JTextField();
		jButton5 = new javax.swing.JButton();
		jLabel6 = new javax.swing.JLabel();
		jTextField10 = new javax.swing.JTextField();
		jButton6 = new javax.swing.JButton();
		jButton7 = new javax.swing.JButton();
		jLabel7 = new javax.swing.JLabel();
		jButton8 = new javax.swing.JButton();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		exp = new javax.swing.JTextField();
		jjj = new javax.swing.JLabel();
		meso = new javax.swing.JTextField();
		jLabel10 = new javax.swing.JLabel();
		drop = new javax.swing.JTextField();
		jLabel11 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		noticMessage = new javax.swing.JTextField();
		jButton9 = new javax.swing.JButton();
		jButton10 = new javax.swing.JButton();
		jButton11 = new javax.swing.JButton();
		jButton12 = new javax.swing.JButton();
		jLabel13 = new javax.swing.JLabel();
		jButton14 = new javax.swing.JButton();
		hottime = new javax.swing.JTextField();
		jButton13 = new javax.swing.JButton();
		jLabel14 = new javax.swing.JLabel();
		jButton15 = new javax.swing.JButton();
		jButton16 = new javax.swing.JButton();
		jButton17 = new javax.swing.JButton();
		jButton18 = new javax.swing.JButton();
		serverMessage = new javax.swing.JTextField();
		jScrollPane1 = new javax.swing.JScrollPane();
		Chat = new javax.swing.JList();
		jLabel16 = new javax.swing.JLabel();
		mesos = new javax.swing.JLabel();
		realcash = new javax.swing.JLabel();
		jLabel19 = new javax.swing.JLabel();
		jLabel20 = new javax.swing.JLabel();
		jLabel21 = new javax.swing.JLabel();
		jScrollPane2 = new javax.swing.JScrollPane();
		chatban = new javax.swing.JList();
		jLabel22 = new javax.swing.JLabel();
		jScrollPane3 = new javax.swing.JScrollPane();
		ban = new javax.swing.JList();
		jLabel15 = new javax.swing.JLabel();
		jLabel17 = new javax.swing.JLabel();
		jScrollPane5 = new javax.swing.JScrollPane();
		동시접속자 = new javax.swing.JList();
		jLabel18 = new javax.swing.JLabel();
		접속자수 = new javax.swing.JLabel();
		jButton19 = new javax.swing.JButton();
		jButton20 = new javax.swing.JButton();

		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosed(java.awt.event.WindowEvent evt) {
				formWindowClosed(evt);
			}
		});

		jButton1.setText("후원지급");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jTextField1.setText("닉네임");

		jTextField2.setText("포인트");

		jLabel1.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
		jLabel1.setText("<후원>");

		jLabel2.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
		jLabel2.setText("<GM 설정>");

		jTextField3.setText("닉네임");

		jButton2.setText("GM설정");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jLabel3.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
		jLabel3.setText("<아이템 지급>");

		jTextField4.setText("닉네임");

		jButton3.setText("아이템 지급");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jTextField5.setText("아이템코드,갯수");

		jLabel4.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
		jLabel4.setText("<메소 지급>");

		jTextField6.setText("닉네임");

		jTextField7.setText("메소");

		jButton4.setText("메소 지급");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		jLabel5.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
		jLabel5.setText("<유저 밴>");

		jTextField8.setText("닉네임(해제는 계정)");

		jTextField9.setText("사유");

		jButton5.setText("벤");
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});

		jLabel6.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
		jLabel6.setText("<채팅 금지>");

		jTextField10.setText("닉네임");

		jButton6.setText("채팅 금지");
		jButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton6ActionPerformed(evt);
			}
		});

		jButton7.setText("채팅 금지 해제");
		jButton7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton7ActionPerformed(evt);
			}
		});

		jLabel7.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
		jLabel7.setText("<채팅 얼리기>");

		jButton8.setText("채팅 얼리기");
		jButton8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton8ActionPerformed(evt);
			}
		});

		jLabel8.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
		jLabel8.setText("<서버 정보 설정>");

		jLabel9.setForeground(new java.awt.Color(51, 0, 255));
		jLabel9.setText("경험치");

		exp.setText("경험치");

		jjj.setForeground(new java.awt.Color(255, 51, 51));
		jjj.setText("메소");

		meso.setText("메소");

		jLabel10.setForeground(new java.awt.Color(51, 0, 153));
		jLabel10.setText("드롭");

		drop.setText("드롭");

		jLabel11.setText("서버 메세지 (서버 상단 메세지)");

		jLabel12.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
		jLabel12.setText("<공지 보내기>");

		noticMessage.setText("공지사항");
		noticMessage.setMaximumSize(new java.awt.Dimension(6, 21));
		noticMessage.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				noticMessageActionPerformed(evt);
			}
		});

		jButton9.setForeground(new java.awt.Color(0, 51, 204));
		jButton9.setText("팝업");
		jButton9.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton9ActionPerformed(evt);
			}
		});

		jButton10.setForeground(new java.awt.Color(255, 0, 204));
		jButton10.setText("분홍");
		jButton10.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton10ActionPerformed(evt);
			}
		});

		jButton11.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
		jButton11.setForeground(new java.awt.Color(255, 204, 51));
		jButton11.setText("쇼인포");
		jButton11.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton11ActionPerformed(evt);
			}
		});

		jButton12.setForeground(new java.awt.Color(153, 0, 204));
		jButton12.setText("엔피시");
		jButton12.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton12ActionPerformed(evt);
			}
		});

		jLabel13.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
		jLabel13.setText("<핫타임>");

		jButton14.setForeground(new java.awt.Color(153, 153, 153));
		jButton14.setText("서버정보 변경");
		jButton14.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton14ActionPerformed(evt);
			}
		});

		hottime.setText("아이템 코드,갯수");

		jButton13.setText("핫타임 지급");
		jButton13.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton13ActionPerformed(evt);
			}
		});

		jLabel14.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
		jLabel14.setText("<서버 관련>");

		jButton15.setText("모두 저장");
		jButton15.setToolTipText("");
		jButton15.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton15ActionPerformed(evt);
			}
		});

		jButton16.setText("모두 로그인 서버로 이동");
		jButton16.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton16ActionPerformed(evt);
			}
		});

		jButton17.setText("서버 종료");
		jButton17.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton17ActionPerformed(evt);
			}
		});

		jButton18.setText("모두 스타플래닛으로 이동");
		jButton18.setToolTipText("");
		jButton18.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton18ActionPerformed(evt);
			}
		});

		serverMessage.setText("서버 상단 메세지");
		serverMessage.setToolTipText("");
		serverMessage.setMaximumSize(new java.awt.Dimension(6, 21));
		serverMessage.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				serverMessageActionPerformed(evt);
			}
		});

		Chat.setForeground(new java.awt.Color(102, 0, 102));
		Chat.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		jScrollPane1.setViewportView(Chat);

		jLabel16.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
		jLabel16.setForeground(new java.awt.Color(255, 51, 102));
		jLabel16.setText("<실시간 채팅 로그>");

		mesos.setFont(new java.awt.Font("굴림", 0, 14)); // NOI18N
		mesos.setForeground(new java.awt.Color(204, 0, 204));
		mesos.setText("서버 총 메소 : ");

		realcash.setFont(new java.awt.Font("굴림", 0, 14)); // NOI18N
		realcash.setForeground(new java.awt.Color(0, 153, 102));
		realcash.setText("서버 총 후원 포인트 : ");

		jLabel19.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
		jLabel19.setText("<서버 총 메소(GM제외), 서버 총 후포(GM제외)>");

		jLabel20.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
		jLabel20.setText("[모든 기록은 마지막 리붓 기준 으로 표시 됩니다.]");

		jLabel21.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
		jLabel21.setForeground(new java.awt.Color(255, 0, 51));
		jLabel21.setText("<채팅 금지자들>");

		chatban.setForeground(new java.awt.Color(255, 0, 51));
		chatban.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				chatbanMouseClicked(evt);
			}
		});
		chatban.addComponentListener(new java.awt.event.ComponentAdapter() {
			public void componentShown(java.awt.event.ComponentEvent evt) {
				chatbanComponentShown(evt);
			}
		});
		chatban.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusGained(java.awt.event.FocusEvent evt) {
				chatbanFocusGained(evt);
			}
		});
		jScrollPane2.setViewportView(chatban);

		jLabel22.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
		jLabel22.setForeground(new java.awt.Color(0, 0, 204));
		jLabel22.setText("<벤 계정들>");

		ban.setForeground(new java.awt.Color(51, 0, 204));
		ban.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				banMouseClicked(evt);
			}
		});
		jScrollPane3.setViewportView(ban);

		jLabel15.setFont(new java.awt.Font("DS가변 교양있는글씨 M", 1, 48)); // NOI18N
		jLabel15.setForeground(new java.awt.Color(0, 0, 153));
		jLabel15.setText("아크스토리");
		jLabel15.setToolTipText("");
		jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabel15MouseClicked(evt);
			}
		});

		jLabel17.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
		jLabel17.setForeground(new java.awt.Color(51, 102, 0));
		jLabel17.setText("<현재 접속중인 유저>");

		동시접속자.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				동시접속자MouseClicked(evt);
			}
		});
		jScrollPane5.setViewportView(동시접속자);

		jLabel18.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
		jLabel18.setText("접속자 수 : ");

		접속자수.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
		접속자수.setText("0");

		jButton19.setText("해제");
		jButton19.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton19ActionPerformed(evt);
			}
		});

		jButton20.setText("옵코드 리셋");
		jButton20.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton20ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout
						.createSequentialGroup().addGroup(layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout
										.createSequentialGroup().addGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(layout.createSequentialGroup().addGap(22, 22, 22)
														.addGroup(layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addGroup(layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																		.addComponent(jLabel11,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				182,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGroup(layout.createSequentialGroup()
																				.addGap(11, 11, 11)
																				.addComponent(exp,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addGap(54, 54, 54).addComponent(meso,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						48,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addComponent(serverMessage,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				273,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(jButton14,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE))
																.addGroup(layout.createSequentialGroup()
																		.addGap(107, 107, 107).addComponent(jButton20,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				169,
																				javax.swing.GroupLayout.PREFERRED_SIZE))))
												.addGroup(layout.createSequentialGroup().addGap(37, 37, 37)
														.addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE,
																48, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(54, 54, 54).addComponent(jjj).addGap(65, 65, 65)
														.addGroup(layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(drop,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(jLabel10)))
												.addGroup(layout.createSequentialGroup().addContainerGap()
														.addGroup(layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(
																		jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE,
																		118, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(jLabel13,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 90,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(
																		jLabel12,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 88,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGroup(layout.createSequentialGroup().addGap(10,
																		10, 10)
																		.addGroup(layout
																				.createParallelGroup(
																						javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(noticMessage,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						273,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addGroup(layout.createSequentialGroup()
																						.addComponent(hottime,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								168,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addPreferredGap(
																								javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																						.addComponent(jButton13))
																				.addGroup(layout
																						.createSequentialGroup()
																						.addComponent(jButton9)
																						.addPreferredGap(
																								javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																						.addComponent(jButton10)
																						.addPreferredGap(
																								javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																						.addComponent(
																								jButton11)
																						.addPreferredGap(
																								javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																						.addComponent(jButton12))))
																.addGroup(layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING,
																				false)
																		.addComponent(jButton18,
																				javax.swing.GroupLayout.Alignment.LEADING,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(jLabel14,
																				javax.swing.GroupLayout.Alignment.LEADING,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				190,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(jButton16,
																				javax.swing.GroupLayout.Alignment.LEADING,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				282, Short.MAX_VALUE)
																		.addComponent(jButton17,
																				javax.swing.GroupLayout.Alignment.LEADING,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(jButton15,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)))))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44,
												Short.MAX_VALUE))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
												.addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 218,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(57, 57, 57)))
						.addGroup(
								layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING,
												javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
												.createSequentialGroup().addGap(0, 36, Short.MAX_VALUE).addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(jButton7,
																javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addGroup(layout.createSequentialGroup().addGroup(layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.TRAILING,
																		false)
																.addComponent(jTextField10,
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jTextField9,
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jTextField8,
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jTextField7,
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jTextField6,
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jTextField5,
																		javax.swing.GroupLayout.Alignment.LEADING,
																		javax.swing.GroupLayout.DEFAULT_SIZE, 154,
																		Short.MAX_VALUE)
																.addComponent(jTextField4,
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jTextField3,
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jTextField2,
																		javax.swing.GroupLayout.Alignment.LEADING,
																		javax.swing.GroupLayout.DEFAULT_SIZE, 154,
																		Short.MAX_VALUE)
																.addComponent(jTextField1,
																		javax.swing.GroupLayout.Alignment.LEADING,
																		javax.swing.GroupLayout.DEFAULT_SIZE, 154,
																		Short.MAX_VALUE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																		.addComponent(jButton2,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(jButton3,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(jButton1,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(jButton4,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(jButton6,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addGroup(layout.createSequentialGroup()
																				.addComponent(jButton5,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						63,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addPreferredGap(
																						javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(jButton19,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						72,
																						javax.swing.GroupLayout.PREFERRED_SIZE))))))
										.addGroup(layout.createSequentialGroup().addGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 88,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 86,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 89,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 73,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel3)
												.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel1)).addGap(0, 0, Short.MAX_VALUE)))
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addGap(29, 29, 29)
										.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										layout.createSequentialGroup()
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 128,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(123, 123, 123)))
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										layout.createSequentialGroup().addComponent(jLabel17).addGap(40, 40, 40))
								.addGroup(layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 167,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGroup(layout.createSequentialGroup().addGap(31, 31, 31)
														.addComponent(jLabel18)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(접속자수)))
										.addGap(18, 18, 18)))
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(mesos, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(realcash, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGroup(layout.createSequentialGroup().addGap(10, 10, 10).addComponent(jLabel20))
								.addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING))
								.addGroup(layout.createSequentialGroup().addGap(18, 18, 18)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(jLabel21).addComponent(jScrollPane2,
														javax.swing.GroupLayout.PREFERRED_SIZE, 106,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(
												layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(layout.createSequentialGroup().addGap(57, 57, 57)
																.addComponent(jScrollPane3,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 101,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
																layout.createSequentialGroup()
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(jLabel22).addGap(14, 14, 14)))))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGroup(layout
								.createParallelGroup(
										javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGroup(layout.createSequentialGroup()
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel8)
														.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE,
																18, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jButton20))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jTextField1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel9).addComponent(jjj).addComponent(jLabel10))
												.addGap(7, 7, 7)
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(meso, javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(jTextField2,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(exp,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(drop,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addGroup(layout.createSequentialGroup().addComponent(jLabel2)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
														.addGroup(layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jButton2).addComponent(jTextField3,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGap(18, 18, 18).addComponent(jLabel3))
												.addGroup(javax.swing.GroupLayout.Alignment.LEADING,
														layout.createSequentialGroup().addComponent(jLabel11)
																.addGap(10, 10, 10)
																.addComponent(serverMessage,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(jButton14)))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(layout.createSequentialGroup().addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addGroup(layout.createSequentialGroup()
																.addComponent(jTextField4,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(jTextField5,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
														.addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE,
																50, Short.MAX_VALUE))
														.addGap(18, 18, 18).addComponent(jLabel4)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addGroup(layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING,
																		false)
																.addGroup(layout.createSequentialGroup()
																		.addGroup(layout
																				.createParallelGroup(
																						javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(jTextField6,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(jLabel13))
																		.addGap(8, 8, 8)
																		.addGroup(layout
																				.createParallelGroup(
																						javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(jTextField7,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(hottime,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(jButton13)))
																.addComponent(jButton4,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)))
												.addGroup(layout.createSequentialGroup().addComponent(jLabel12)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(noticMessage,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addGroup(layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(jButton9).addComponent(jButton10)
																.addComponent(jButton11).addComponent(jButton12))))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel5).addComponent(jLabel14,
														javax.swing.GroupLayout.PREFERRED_SIZE, 15,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jButton19, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addGroup(layout.createSequentialGroup().addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jTextField8,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jButton15))
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addGroup(layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(jTextField9,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(jButton16))))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jButton17)
												.addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jButton18)
												.addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jButton6))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(layout.createSequentialGroup().addComponent(jButton7)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(jLabel7)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
												.addGroup(layout.createSequentialGroup().addGap(4, 4, 4).addComponent(
														jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
								.addGroup(layout.createSequentialGroup().addGroup(layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup().addContainerGap()
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(jLabel17).addComponent(jLabel16))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING,
																false)
														.addComponent(jScrollPane1,
																javax.swing.GroupLayout.PREFERRED_SIZE, 537,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(layout
																.createSequentialGroup()
																.addGroup(layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(jLabel18,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(접속자수))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(jScrollPane5,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 503,
																		javax.swing.GroupLayout.PREFERRED_SIZE))))
										.addGroup(layout.createSequentialGroup().addGap(11, 11, 11)
												.addComponent(jLabel19)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addComponent(jLabel20)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addComponent(mesos)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(realcash).addGap(18, 18, 18)
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel21).addComponent(jLabel22,
																javax.swing.GroupLayout.PREFERRED_SIZE, 15,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(jScrollPane3,
																javax.swing.GroupLayout.DEFAULT_SIZE, 426,
																Short.MAX_VALUE)
														.addComponent(jScrollPane2))))
										.addGap(0, 2, Short.MAX_VALUE)))
						.addContainerGap()));

		jLabel15.getAccessibleContext().setAccessibleName("ARCSTORY");

		pack();
	}// </editor-fold>//GEN-END:initComponents

	public void 환율정보() {
		long meso = 0;
		int realcash = 0;
		try {
			ResultSet ps = MYSQL.getConnection().prepareStatement("SELECT * FROM characters WHERE gm = 0")
					.executeQuery();
			while (ps.next()) {
				meso += ps.getLong("meso");
			}
			ps.close();
			ps = MYSQL.getConnection().prepareStatement("SELECT * FROM storages").executeQuery();
			while (ps.next()) {
				meso += ps.getLong("meso");
			}
			mesos.setText(mesos.getText() + meso + "$");
			ps = MYSQL.getConnection().prepareStatement("SELECT * FROM accounts WHERE gm = 0").executeQuery();
			while (ps.next()) {
				realcash += ps.getInt("realcash");
			}
			ps.close();
			this.realcash.setText(this.realcash.getText() + realcash + "$");
		} catch (SQLException ex) {

		}
	}

	public void 벤() {
		try {
			ResultSet ps = MYSQL.getConnection().prepareStatement("SELECT * FROM accounts WHERE gm = 0").executeQuery();
			while (ps.next()) {
				if (ps.getInt("banned") != 0) {
					BanList.addElement(ps.getString("name"));
				}
			}
			ps.close();
			ban.setModel(BanList);
		} catch (SQLException ex) {

		}
	}

	public void 채팅금지() {
		String name = "";
		try {
			ResultSet rs = MYSQL.getConnection().prepareStatement("SELECT * FROM characters WHERE gm = 0")
					.executeQuery();
			while (rs.next()) {
				if (rs.getString("chatban").equals("true")) {
					ChatbanList.addElement(rs.getString("name"));
				}
			}
			rs.close();
			chatban.setModel(ChatbanList);
		} catch (SQLException ex) {
			ex.printStackTrace();
		}
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		boolean check = false;
		for (ChannelServer cs : ChannelServer.getAllInstances()) {
			MapleCharacter hp = null;
			hp = cs.getPlayerStorage().getCharacterByName(this.jTextField1.getText());
			if (hp == null && !check) {
				check = false;
			} else if (hp != null) {
				check = true;
				hp.gainRC(Integer.parseInt(this.jTextField2.getText()));
				hp.dropMessage(5, "서버로 부터 [" + Integer.parseInt(this.jTextField2.getText()) + "] 후원 포인트를 지급 받으셨습니다.");
				JOptionPane.showMessageDialog(null, jTextField1.getText() + "님에게 후원 포인트를 지급 하였습니다.");
				초기화();
				return;
			}
		}
		if (!check) {
			JOptionPane.showMessageDialog(null, "플레이어가 접속 중이지 않습니다.");
		}

	}// GEN-LAST:event_jButton1ActionPerformed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		boolean check = false;
		for (ChannelServer cs : ChannelServer.getAllInstances()) {
			MapleCharacter hp = null;
			hp = cs.getPlayerStorage().getCharacterByName(this.jTextField3.getText());
			if (hp == null && !check) {
				check = false;
			} else if (hp != null) {
				check = true;
				hp.setGMLevel((byte) 6);
				hp.dropShowInfo("GM설정이 되었습니다.");
				JOptionPane.showMessageDialog(null, "GM설정을 하였습니다.");
				초기화();
				return;
			}
		}
		if (!check) {
			JOptionPane.showMessageDialog(null, "플레이어가 접속 중이지 않습니다.");
		}
	}// GEN-LAST:event_jButton2ActionPerformed

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
		boolean check = false;
		for (ChannelServer cs : ChannelServer.getAllInstances()) {
			MapleCharacter hp = null;
			hp = cs.getPlayerStorage().getCharacterByName(this.jTextField4.getText());
			if (hp == null && !check) {
				check = false;
			} else if (hp != null) {
				check = true;
				String a[] = this.jTextField5.getText().split(",");
				int itemid = Integer.parseInt(a[0]);
				short quantity = Short.parseShort(a[1]);
				hp.gainItem(itemid, quantity, false, -1, null);
				hp.dropMessage(1, "아이템을 지급 받으셨습니다.");
				JOptionPane.showMessageDialog(null, "아이템을 지급 하였습니다.");
				초기화();
				return;
			}
		}
		if (!check) {
			JOptionPane.showMessageDialog(null, "플레이어가 접속 중이지 않습니다.");
		}
	}// GEN-LAST:event_jButton3ActionPerformed

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed
		boolean check = false;
		for (ChannelServer cs : ChannelServer.getAllInstances()) {
			MapleCharacter hp = null;
			hp = cs.getPlayerStorage().getCharacterByName(this.jTextField6.getText());
			if (hp == null && !check) {
				check = false;
			} else if (hp != null) {
				check = true;
				hp.gainMeso(Long.parseLong(this.jTextField7.getText()), true);
				hp.dropMessage(1, "메소를 지급 받으셨습니다.");
				JOptionPane.showMessageDialog(null, "메소를 지급 하였습니다.");
				초기화();
				return;
			}
		}
		if (!check) {
			JOptionPane.showMessageDialog(null, "플레이어가 접속 중이지 않습니다.");
		}
	}// GEN-LAST:event_jButton4ActionPerformed

	public static void 서버정보불러오기() {
		for (ChannelServer cserv : ChannelServer.getAllInstances()) {
			exp.setText(cserv.getExpRate() + "");
			drop.setText(cserv.getDropRate() + "");
			meso.setText(cserv.getMesoRate() + "");
			serverMessage.setText(cserv.getServerMessage());
			break;
		}
	}

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton5ActionPerformed
		boolean check = false;
		for (ChannelServer cs : ChannelServer.getAllInstances()) {
			MapleCharacter hp = null;
			hp = cs.getPlayerStorage().getCharacterByName(this.jTextField8.getText());
			if (hp == null && !check) {
				check = false;
			} else if (hp != null) {
				final MapleClient c = null;
				check = true;
				hp.ban(jTextField8.getText(), true, false);
				c.getSession().write(MainPacketCreator.getNPCTalk(2007, (byte) 0,
						"해당 계정은 지금부터 사용 할 수 없습니다.\r\n(3초 뒤 자동적으로 종료 됩니다.)", "00 00", (byte) 2));
				BanList.addElement(hp.getClient().getAccountName());
				ban.setModel(BanList);
				Timer.EtcTimer tMan = Timer.EtcTimer.getInstance();
				tMan.schedule(new Runnable() {
					@Override
					public void run() {
						c.disconnect(true, (c.getLoginState() == 4 || c.getLoginState() == 5));
						c.getSession().closeNow();
						c.getSession().closeNow();
					}
				}, 3000);
				JOptionPane.showMessageDialog(null, jTextField8.getText() + "유저를 밴 하였습니다.");
				초기화();
				return;
			}
		}
		if (!check) {
			JOptionPane.showMessageDialog(null, "플레이어가 접속 중이지 않습니다.");
		}
	}// GEN-LAST:event_jButton5ActionPerformed

	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton6ActionPerformed
		boolean check = false;
		for (ChannelServer cs : ChannelServer.getAllInstances()) {
			MapleCharacter hp = null;
			hp = cs.getPlayerStorage().getCharacterByName(this.jTextField10.getText());
			if (hp == null && !check) {
				check = false;
			} else if (hp != null) {
				check = true;
				hp.setChatban("true");
				hp.dropMessage(1, "채팅 금지를 당하였습니다.");
				JOptionPane.showMessageDialog(null, "채팅 금지를 하였습니다.");
				ChatbanList.addElement(hp.getName());
				chatban.setModel(ChatbanList);
				초기화();
				return;
			}
		}
		if (!check) {
			JOptionPane.showMessageDialog(null, "플레이어가 접속 중이지 않습니다.");
		}
	}// GEN-LAST:event_jButton6ActionPerformed

	private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton7ActionPerformed
		boolean check = false;
		for (ChannelServer cs : ChannelServer.getAllInstances()) {
			MapleCharacter hp = null;
			hp = cs.getPlayerStorage().getCharacterByName(this.jTextField10.getText());
			if (hp == null && !check) {
				check = false;
			} else if (hp != null) {
				check = true;
				hp.setChatban("false");
				hp.dropMessage(1, "채팅 금지가 해제 되었습니다.");
				JOptionPane.showMessageDialog(null, "채팅 금지를 해제 하였습니다.");
				ChatList.removeElement(jTextField10.getText());
				chatban.setModel(ChatList);
				초기화();
				return;
			}
		}
		if (!check) {
			JOptionPane.showMessageDialog(null, "플레이어가 접속 중이지 않습니다.");
		}
	}// GEN-LAST:event_jButton7ActionPerformed

	private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton8ActionPerformed
		if (!WorldCommunity.isFreeze) {
			WorldCommunity.isFreeze = true;
			this.jButton8.setText("채팅 녹이기");
			WorldBroadcasting.broadcastMessage(MainPacketCreator.serverNotice(1, "채팅이 얼었습니다."));
			JOptionPane.showMessageDialog(null, "채팅을 얼렸습니다.");
		} else {
			WorldCommunity.isFreeze = false;
			this.jButton8.setText("채팅 얼리기");
			WorldBroadcasting.broadcastMessage(MainPacketCreator.serverNotice(1, "채팅이 녹았습니다."));
			JOptionPane.showMessageDialog(null, "채팅을 녹였습니다.");
		}
	}// GEN-LAST:event_jButton8ActionPerformed

	private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton13ActionPerformed
		String b[] = this.hottime.getText().split(",");
		int itemid = Integer.parseInt(b[0]);
		short quantity = Short.parseShort(b[1]);
		for (ChannelServer cs : ChannelServer.getAllInstances()) {
			for (MapleCharacter chr : cs.getPlayerStorage().getAllCharacters().values()) {
				chr.gainItem(itemid, quantity, false, -1, null);
			}
		}
		WorldBroadcasting.broadcastMessage(MainPacketCreator.serverNotice(1, "핫타임 아이템을 지급 받았습니다."));
		JOptionPane.showMessageDialog(null, "핫타임 아이템을 지급 하였습니다.");
	}// GEN-LAST:event_jButton13ActionPerformed

	private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton14ActionPerformed
		for (int i = 0; i < ServerConstants.serverCount; i++) {
			ChannelServer.getInstance(i).setExpRate(Integer.parseInt(this.exp.getText()));
			ChannelServer.getInstance(i).setMesoRate((byte) Integer.parseInt(this.meso.getText()));
			ChannelServer.getInstance(i).setDropRate(Integer.parseInt(this.drop.getText()));
			ChannelServer.getInstance(i).setServerMessage(this.serverMessage.getText());
		}
		JOptionPane.showMessageDialog(null, "서버 정보를 변경 하였습니다.");
	}// GEN-LAST:event_jButton14ActionPerformed

	private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton9ActionPerformed
		공지사항(1, this.noticMessage.getText());
	}// GEN-LAST:event_jButton9ActionPerformed

	private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton10ActionPerformed
		공지사항(5, this.noticMessage.getText());
	}// GEN-LAST:event_jButton10ActionPerformed

	private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton11ActionPerformed
		공지사항(-1, this.noticMessage.getText());
	}// GEN-LAST:event_jButton11ActionPerformed

	private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton12ActionPerformed
		공지사항(-2, this.noticMessage.getText());
	}// GEN-LAST:event_jButton12ActionPerformed

	private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton15ActionPerformed
		for (ChannelServer cs : ChannelServer.getAllInstances()) {
			for (MapleCharacter chr : cs.getPlayerStorage().getAllCharacters().values()) {
				chr.saveToDB(false, false);
			}
		}
		JOptionPane.showMessageDialog(null, "모두 저장을 완료 하였습니다.");
	}// GEN-LAST:event_jButton15ActionPerformed

	private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton16ActionPerformed
		for (ChannelServer cserv : ChannelServer.getAllInstances()) {
			cserv.getPlayerStorage().disconnectAll();
		}
		JOptionPane.showMessageDialog(null, "모든 플레이어가 로그인 서버로 이동 되었습니다.");
	}// GEN-LAST:event_jButton16ActionPerformed

	private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton17ActionPerformed

		for (ChannelServer cs : ChannelServer.getAllInstances()) {
			cs.closeAllMerchant();
			cs.saveAllMerchant();
			cs.getPlayerStorage().disconnectAll();
			// LoginServer.getInstance().shutdown();
		}
		JOptionPane.showMessageDialog(null, "서버를 종료 하였습니다.");
	}// GEN-LAST:event_jButton17ActionPerformed

	private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton18ActionPerformed
		MapleMap map = null;
		for (ChannelServer cs : ChannelServer.getAllInstances()) {
			for (MapleCharacter hp : cs.getPlayerStorage().getAllCharacters().values()) {
				hp.warp(340000100);
			}
		}
		JOptionPane.showMessageDialog(null, "모든 플레이어를 스타플래닛으로 이동 시켰습니다.");
	}// GEN-LAST:event_jButton18ActionPerformed

	private void chatbanMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_chatbanMouseClicked

	}// GEN-LAST:event_chatbanMouseClicked

	private void chatbanFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_chatbanFocusGained
		// TODO add your handling code here:
	}// GEN-LAST:event_chatbanFocusGained

	private void chatbanComponentShown(java.awt.event.ComponentEvent evt) {// GEN-FIRST:event_chatbanComponentShown
		// JOptionPane.showMessageDialog(null,chatban.getDropTarget().toString());
	}// GEN-LAST:event_chatbanComponentShown

	private void 동시접속자MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_동시접속자MouseClicked
		try {
			if (동시접속자.getModel() != null) {
				String name = 동시접속자.getModel().getElementAt(동시접속자.getSelectedIndex()).toString();
				jTextField1.setText(name);
				jTextField3.setText(name);
				jTextField4.setText(name);
				jTextField6.setText(name);
				jTextField8.setText(name);
				jTextField10.setText(name);
			}
		} catch (Exception e) {

		}
	}// GEN-LAST:event_동시접속자MouseClicked

	private void banMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_banMouseClicked
		try {
			jTextField8.setText(ban.getModel().getElementAt(ban.getSelectedIndex()).toString());
		} catch (Exception e) {

		}
	}// GEN-LAST:event_banMouseClicked

	private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton19ActionPerformed
		try {
			Connection con = MYSQL.getConnection();
			PreparedStatement ps = con.prepareStatement("UPDATE accounts SET banned = ?, banreason = ? WHERE name = ?");
			ps.setInt(1, 0);
			ps.setString(2, "");
			ps.setString(3, jTextField8.getText());
			ps.executeUpdate();
			ps.close();
		} catch (SQLException ex) {
			ex.printStackTrace();
		}
		BanList.removeElement(jTextField8.getText());
		ban.setModel(BanList);
		JOptionPane.showMessageDialog(null, jTextField8.getText() + "님의 게임이용 제한을 해제 하였습니다.");
		초기화();
	}// GEN-LAST:event_jButton19ActionPerformed

	private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel15MouseClicked
		SearchToCode.main(null);
	}// GEN-LAST:event_jLabel15MouseClicked

	private void formWindowClosed(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowClosed

	}// GEN-LAST:event_formWindowClosed

	private void serverMessageActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_serverMessageActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_serverMessageActionPerformed

	private void noticMessageActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_noticMessageActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_noticMessageActionPerformed

	private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton20ActionPerformed
		// TODO add your handling code here:
		SendPacketOpcode.loadOpcode();
		RecvPacketOpcode.loadOpcode();
		System.out.println("[알림] 옵코드 재설정이 완료되었습니다.");
	}// GEN-LAST:event_jButton20ActionPerformed

	public String 아이피(String name) throws SQLException {
		String a = "";
		PreparedStatement ps2 = MYSQL.getConnection().prepareStatement("SELECT * FROM accounts WHERE name = ?");
		ps2.setString(1, name);
		ResultSet con = ps2.executeQuery();
		while (con.next()) {
			a = con.getString("ip");
		}
		ps2.close();
		con.close();
		return a;
	}

	public void 초기화() {
		String name = "닉네임";
		jTextField1.setText(name);
		jTextField3.setText(name);
		jTextField4.setText(name);
		jTextField6.setText(name);
		jTextField8.setText("닉네임(해제는 계정)");
		jTextField10.setText(name);
	}

	public void 공지사항(int i, String text) {
		if (i == -1) {
			WorldBroadcasting.broadcastMessage(UIPacket.showInfo(text));
		} else if (i == -2) {
			WorldBroadcasting.broadcastMessage(MainPacketCreator.getNPCTalk(2007, (byte) 0, text, "00 00", (byte) 0));
		} else {
			WorldBroadcasting.broadcastMessage(MainPacketCreator.serverNotice(i, text));
		}
		JOptionPane.showMessageDialog(null, "[" + text + "] 내용을 모든 플레이어에게 알렸습니다.");
	}

	public static void 동접(String a) {
		try {
			현재접속자.addElement(a);
			동시접속자.setModel(현재접속자);
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	public static void 동접제거(String a) {
		현재접속자.removeElement(a);
		동시접속자.setModel(현재접속자);
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ControlUnit().setVisible(true);
			}
		});
	}

	public static DefaultListModel ChatList = new DefaultListModel();
	public static DefaultListModel 현재접속자 = new DefaultListModel();
	private DefaultListModel ChatbanList = new DefaultListModel();
	private DefaultListModel BanList = new DefaultListModel();
	private transient ScheduledFuture<?> chattime;
	private int timeo = 0;
	// Variables declaration - do not modify//GEN-BEGIN:variables
	public static javax.swing.JList Chat;
	private javax.swing.JList ban;
	private javax.swing.JList chatban;
	private static javax.swing.JTextField drop;
	private static javax.swing.JTextField exp;
	private javax.swing.JTextField hottime;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton10;
	private javax.swing.JButton jButton11;
	private javax.swing.JButton jButton12;
	private javax.swing.JButton jButton13;
	private javax.swing.JButton jButton14;
	private javax.swing.JButton jButton15;
	private javax.swing.JButton jButton16;
	private javax.swing.JButton jButton17;
	private javax.swing.JButton jButton18;
	private javax.swing.JButton jButton19;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton20;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	private javax.swing.JButton jButton8;
	private javax.swing.JButton jButton9;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel18;
	private javax.swing.JLabel jLabel19;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel20;
	private javax.swing.JLabel jLabel21;
	private javax.swing.JLabel jLabel22;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JScrollPane jScrollPane5;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField10;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	private javax.swing.JTextField jTextField5;
	private javax.swing.JTextField jTextField6;
	private javax.swing.JTextField jTextField7;
	private javax.swing.JTextField jTextField8;
	private javax.swing.JTextField jTextField9;
	private javax.swing.JLabel jjj;
	private static javax.swing.JTextField meso;
	private javax.swing.JLabel mesos;
	private javax.swing.JTextField noticMessage;
	private javax.swing.JLabel realcash;
	private static javax.swing.JTextField serverMessage;
	public static javax.swing.JList 동시접속자;
	public static javax.swing.JLabel 접속자수;
	// End of variables declaration//GEN-END:variables
}
